// Generated by meta.cpp

#pragma once

#include "lumscript/capi.h"
#include <string.h>
#include "core/stream.h"
#include "engine/reflection.h"
#include "engine/world.h"
#include "animation/animation_module.h"
#include "audio/audio_module.h"
#include "engine/core.h"
#include "lua/lua_script_system.h"
#include "navigation/navigation_module.h"
#include "physics/physics_module.h"
#include "renderer/render_module.h"
#include "ui/ui_module.h"

namespace Lumix::LumScript::generated {
	
	static void lumscript_world_animation(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("property_animator"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_audio(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("echo_zone"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_core(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("spline"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_lua_script(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("lua_script"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_navigation(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("navmesh_zone"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_physics(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("physical_heightfield"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_renderer(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("camera"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_world_ui(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		IModule* module = world->getModule(reflection::getComponentType("ui_3d"));
		if (!module) { ls_push_null(runtime); return; }
		ls_push_ptr(runtime, module);
	}
	
	static void lumscript_entity_property_animator(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("property_animator");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_animator(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("animator");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_animable(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("animable");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_echo_zone(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("echo_zone");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_chorus_zone(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("chorus_zone");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_audio_listener(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("audio_listener");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_ambient_sound(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("ambient_sound");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_spline(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("spline");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_signal(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("signal");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_lua_script(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("lua_script");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_lua_script_inline(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("lua_script_inline");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_navmesh_zone(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("navmesh_zone");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_navmesh_agent(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("navmesh_agent");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_physical_heightfield(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("physical_heightfield");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_d6_joint(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("d6_joint");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_distance_joint(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("distance_joint");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_hinge_joint(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("hinge_joint");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_spherical_joint(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("spherical_joint");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_physical_controller(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("physical_controller");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_rigid_actor(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("rigid_actor");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_wheel(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("wheel");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_vehicle(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("vehicle");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_physical_instanced_cube(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("physical_instanced_cube");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_physical_instanced_mesh(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("physical_instanced_mesh");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_camera(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("camera");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_decal(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("decal");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_environment(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("environment");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_point_light(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("point_light");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_reflection_probe(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("reflection_probe");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_environment_probe(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("environment_probe");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_bone_attachment(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("bone_attachment");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_particle_emitter(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("particle_emitter");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_instanced_model(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("instanced_model");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_model_instance(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("model_instance");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_curve_decal(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("curve_decal");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_terrain(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("terrain");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_procedural_geom(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("procedural_geom");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_entity_ui_3d(ls_runtime* runtime) {
		World* world = (World*)ls_to_ptr(runtime, -1);
		i32 entity_idx = ls_to_i32(runtime, -2);
		const ComponentType component_type = reflection::getComponentType("ui_3d");
		if (!world->hasComponent(EntityRef(entity_idx), component_type)) {
			ls_push_null(runtime);
			return;
		}
		ls_push_i32(runtime, entity_idx);
		ls_push_ptr(runtime, world);
	}
	
	static void lumscript_audio_setMasterVolume_0(ls_runtime* runtime) {
		auto* module = static_cast<AudioModule*>(ls_to_ptr(runtime, -1));
		module->setMasterVolume(ls_to_f32(runtime, -1));
	}
	
	static void lumscript_physics_raycast_1(ls_runtime* runtime) {
		auto* module = static_cast<PhysicsModule*>(ls_to_ptr(runtime, -1));
		auto ret = module->raycast({}, {}, ls_to_f32(runtime, -3), EntityPtr{});
	}
	
	static void lumscript_physics_setGravity_2(ls_runtime* runtime) {
		auto* module = static_cast<PhysicsModule*>(ls_to_ptr(runtime, -1));
		module->setGravity({});
	}
	
	static void lumscript_renderer_setActiveCamera_3(ls_runtime* runtime) {
		auto* module = static_cast<RenderModule*>(ls_to_ptr(runtime, -1));
		module->setActiveCamera({});
	}
	
	static void lumscript_renderer_setActiveEnvironment_4(ls_runtime* runtime) {
		auto* module = static_cast<RenderModule*>(ls_to_ptr(runtime, -1));
		module->setActiveEnvironment({});
	}
	
	static void lumscript_ui_isReady_5(ls_runtime* runtime) {
		auto* module = static_cast<UIModule*>(ls_to_ptr(runtime, -1));
		auto ret = module->isReady();
		ls_push_bool(runtime, ret);
	}
	
	static void registerGeneratedEngineImport(HashMap<StringView, ls_native_fn>& functions) {
		functions.insert(StringView("core:entity.property_animator"), &lumscript_entity_property_animator);
		functions.insert(StringView("core:entity.animator"), &lumscript_entity_animator);
		functions.insert(StringView("core:entity.animable"), &lumscript_entity_animable);
		functions.insert(StringView("core:entity.echo_zone"), &lumscript_entity_echo_zone);
		functions.insert(StringView("core:entity.chorus_zone"), &lumscript_entity_chorus_zone);
		functions.insert(StringView("core:entity.audio_listener"), &lumscript_entity_audio_listener);
		functions.insert(StringView("core:entity.ambient_sound"), &lumscript_entity_ambient_sound);
		functions.insert(StringView("core:entity.spline"), &lumscript_entity_spline);
		functions.insert(StringView("core:entity.signal"), &lumscript_entity_signal);
		functions.insert(StringView("core:entity.lua_script"), &lumscript_entity_lua_script);
		functions.insert(StringView("core:entity.lua_script_inline"), &lumscript_entity_lua_script_inline);
		functions.insert(StringView("core:entity.navmesh_zone"), &lumscript_entity_navmesh_zone);
		functions.insert(StringView("core:entity.navmesh_agent"), &lumscript_entity_navmesh_agent);
		functions.insert(StringView("core:entity.physical_heightfield"), &lumscript_entity_physical_heightfield);
		functions.insert(StringView("core:entity.d6_joint"), &lumscript_entity_d6_joint);
		functions.insert(StringView("core:entity.distance_joint"), &lumscript_entity_distance_joint);
		functions.insert(StringView("core:entity.hinge_joint"), &lumscript_entity_hinge_joint);
		functions.insert(StringView("core:entity.spherical_joint"), &lumscript_entity_spherical_joint);
		functions.insert(StringView("core:entity.physical_controller"), &lumscript_entity_physical_controller);
		functions.insert(StringView("core:entity.rigid_actor"), &lumscript_entity_rigid_actor);
		functions.insert(StringView("core:entity.wheel"), &lumscript_entity_wheel);
		functions.insert(StringView("core:entity.vehicle"), &lumscript_entity_vehicle);
		functions.insert(StringView("core:entity.physical_instanced_cube"), &lumscript_entity_physical_instanced_cube);
		functions.insert(StringView("core:entity.physical_instanced_mesh"), &lumscript_entity_physical_instanced_mesh);
		functions.insert(StringView("core:entity.camera"), &lumscript_entity_camera);
		functions.insert(StringView("core:entity.decal"), &lumscript_entity_decal);
		functions.insert(StringView("core:entity.environment"), &lumscript_entity_environment);
		functions.insert(StringView("core:entity.point_light"), &lumscript_entity_point_light);
		functions.insert(StringView("core:entity.reflection_probe"), &lumscript_entity_reflection_probe);
		functions.insert(StringView("core:entity.environment_probe"), &lumscript_entity_environment_probe);
		functions.insert(StringView("core:entity.bone_attachment"), &lumscript_entity_bone_attachment);
		functions.insert(StringView("core:entity.particle_emitter"), &lumscript_entity_particle_emitter);
		functions.insert(StringView("core:entity.instanced_model"), &lumscript_entity_instanced_model);
		functions.insert(StringView("core:entity.model_instance"), &lumscript_entity_model_instance);
		functions.insert(StringView("core:entity.curve_decal"), &lumscript_entity_curve_decal);
		functions.insert(StringView("core:entity.terrain"), &lumscript_entity_terrain);
		functions.insert(StringView("core:entity.procedural_geom"), &lumscript_entity_procedural_geom);
		functions.insert(StringView("core:entity.ui_3d"), &lumscript_entity_ui_3d);
		functions.insert(StringView("core:world.animation"), &lumscript_world_animation);
		functions.insert(StringView("core:world.audio"), &lumscript_world_audio);
		functions.insert(StringView("core:world.core"), &lumscript_world_core);
		functions.insert(StringView("core:world.lua_script"), &lumscript_world_lua_script);
		functions.insert(StringView("core:world.navigation"), &lumscript_world_navigation);
		functions.insert(StringView("core:world.physics"), &lumscript_world_physics);
		functions.insert(StringView("core:world.renderer"), &lumscript_world_renderer);
		functions.insert(StringView("core:world.ui"), &lumscript_world_ui);
		functions.insert(StringView("core:audio.setMasterVolume"), &lumscript_audio_setMasterVolume_0);
		functions.insert(StringView("core:physics.raycast"), &lumscript_physics_raycast_1);
		functions.insert(StringView("core:physics.setGravity"), &lumscript_physics_setGravity_2);
		functions.insert(StringView("core:renderer.setActiveCamera"), &lumscript_renderer_setActiveCamera_3);
		functions.insert(StringView("core:renderer.setActiveEnvironment"), &lumscript_renderer_setActiveEnvironment_4);
		functions.insert(StringView("core:ui.isReady"), &lumscript_ui_isReady_5);
	}
	
} // namespace Lumix::LumScript::generated
