// Generated by meta.cpp

reflection::build_module("lumscript")
	.cmp<&LumScriptModule::createLumScript, &LumScriptModule::destroyLumScript>("lumscript", "LumScript / Script")
		.function<(void (LumScriptModule::*)(EntityRef entity))&LumScriptModule::createScript>("createScript")
		.function<(void (LumScriptModule::*)(EntityRef entity))&LumScriptModule::destroyScript>("destroyScript")
		.begin_array<&LumScriptModule::getLumScriptCount, &LumScriptModule::addLumScript, &LumScriptModule::removeLumScript>("scripts")
		.end_array()
;

