// Generated by meta.cpp

#define XXH_STATIC_LINKING_ONLY
#include "xxhash/xxhash.h"

namespace black {
	
	void registerLuaAPI(lua_State* L) {
		lua_newtable(L);
		lua_setglobal(L, "black.hModules");
	}
}

