// Generated by meta.cpp

reflection::build_module("lua_script")
	.cmp<&LuaScriptModule::createScript, &LuaScriptModule::destroyScript>("lua_script", "Lua / File")
		.begin_array<&LuaScriptModule::getScriptCount, &LuaScriptModule::addScript, &LuaScriptModule::removeScript>("scripts")
		.prop<&LuaScriptModule::isScriptEnabled, &LuaScriptModule::enableScript>("Enabled")
		.prop<&LuaScriptModule::getScriptPath, &LuaScriptModule::setScriptPath>("Path")
			.resourceAttribute(LuaScript::TYPE)
		.blob_property<&LuaScriptModule::getScriptBlob, &LuaScriptModule::setScriptBlob>("Blob")
		.end_array()
	.cmp<&LuaScriptModule::createInlineScript, &LuaScriptModule::destroyInlineScript>("lua_script_inline", "Lua / Inline")
		.prop<&LuaScriptModule::getInlineScriptCode, &LuaScriptModule::setInlineScriptCode>("Code")
			.multilineAttribute()
;

