// Generated by meta.cpp

reflection::build_module("ui")
	.function<(ui::Document* (UIModule::*)())&UIModule::getDocument>("getDocument")
	.function<(bool (UIModule::*)())&UIModule::isReady>("isReady")
	.cmp<&UIModule::createUI3D, &UIModule::destroyUI3D>("ui_3d", "UI / 3D")
		.prop<&UIModule::getUI3DPath, &UIModule::setUI3DPath>("Source")
			.resourceAttribute(ui::DocumentResource::TYPE)
		.prop<&UIModule::getUI3DVirtualSize, &UIModule::setUI3DVirtualSize>("Virtual size")
		.prop<&UIModule::getUI3DOrientToCamera, &UIModule::setUI3DOrientToCamera>("Orient to camera")
;

