// generated by meta.cpp
#include "engine/lumix.h"
#include "core/string.h"
namespace Lumix::types {
extern const ComponentType property_animator = reflection::getComponentType("property_animator");
extern const ComponentType animator = reflection::getComponentType("animator");
extern const ComponentType animable = reflection::getComponentType("animable");
extern const ComponentType echo_zone = reflection::getComponentType("echo_zone");
extern const ComponentType chorus_zone = reflection::getComponentType("chorus_zone");
extern const ComponentType audio_listener = reflection::getComponentType("audio_listener");
extern const ComponentType ambient_sound = reflection::getComponentType("ambient_sound");
extern const ComponentType spline = reflection::getComponentType("spline");
extern const ComponentType signal = reflection::getComponentType("signal");
extern const ComponentType gui_canvas = reflection::getComponentType("gui_canvas");
extern const ComponentType gui_render_target = reflection::getComponentType("gui_render_target");
extern const ComponentType gui_input_field = reflection::getComponentType("gui_input_field");
extern const ComponentType gui_rect = reflection::getComponentType("gui_rect");
extern const ComponentType gui_button = reflection::getComponentType("gui_button");
extern const ComponentType gui_image = reflection::getComponentType("gui_image");
extern const ComponentType gui_text = reflection::getComponentType("gui_text");
extern const ComponentType lua_script = reflection::getComponentType("lua_script");
extern const ComponentType lua_script_inline = reflection::getComponentType("lua_script_inline");
extern const ComponentType navmesh_zone = reflection::getComponentType("navmesh_zone");
extern const ComponentType navmesh_agent = reflection::getComponentType("navmesh_agent");
extern const ComponentType physical_heightfield = reflection::getComponentType("physical_heightfield");
extern const ComponentType d6_joint = reflection::getComponentType("d6_joint");
extern const ComponentType distance_joint = reflection::getComponentType("distance_joint");
extern const ComponentType hinge_joint = reflection::getComponentType("hinge_joint");
extern const ComponentType spherical_joint = reflection::getComponentType("spherical_joint");
extern const ComponentType physical_controller = reflection::getComponentType("physical_controller");
extern const ComponentType rigid_actor = reflection::getComponentType("rigid_actor");
extern const ComponentType wheel = reflection::getComponentType("wheel");
extern const ComponentType vehicle = reflection::getComponentType("vehicle");
extern const ComponentType physical_instanced_cube = reflection::getComponentType("physical_instanced_cube");
extern const ComponentType physical_instanced_mesh = reflection::getComponentType("physical_instanced_mesh");
extern const ComponentType camera = reflection::getComponentType("camera");
extern const ComponentType decal = reflection::getComponentType("decal");
extern const ComponentType environment = reflection::getComponentType("environment");
extern const ComponentType point_light = reflection::getComponentType("point_light");
extern const ComponentType reflection_probe = reflection::getComponentType("reflection_probe");
extern const ComponentType environment_probe = reflection::getComponentType("environment_probe");
extern const ComponentType bone_attachment = reflection::getComponentType("bone_attachment");
extern const ComponentType particle_emitter = reflection::getComponentType("particle_emitter");
extern const ComponentType instanced_model = reflection::getComponentType("instanced_model");
extern const ComponentType model_instance = reflection::getComponentType("model_instance");
extern const ComponentType curve_decal = reflection::getComponentType("curve_decal");
extern const ComponentType terrain = reflection::getComponentType("terrain");
extern const ComponentType procedural_geom = reflection::getComponentType("procedural_geom");
extern const ComponentType jolt_mesh = reflection::getComponentType("jolt_mesh");
extern const ComponentType jolt_sphere = reflection::getComponentType("jolt_sphere");
extern const ComponentType jolt_box = reflection::getComponentType("jolt_box");
extern const ComponentType jolt_body = reflection::getComponentType("jolt_body");
extern const ComponentType js_script = reflection::getComponentType("js_script");
}
