// generated by meta.cpp
#include "engine/lumix.h"
namespace Lumix::types {
LUMIX_ENGINE_API extern const ComponentType property_animator;
LUMIX_ENGINE_API extern const ComponentType animator;
LUMIX_ENGINE_API extern const ComponentType animable;
LUMIX_ENGINE_API extern const ComponentType echo_zone;
LUMIX_ENGINE_API extern const ComponentType chorus_zone;
LUMIX_ENGINE_API extern const ComponentType audio_listener;
LUMIX_ENGINE_API extern const ComponentType ambient_sound;
LUMIX_ENGINE_API extern const ComponentType spline;
LUMIX_ENGINE_API extern const ComponentType signal;
LUMIX_ENGINE_API extern const ComponentType gui_canvas;
LUMIX_ENGINE_API extern const ComponentType gui_render_target;
LUMIX_ENGINE_API extern const ComponentType gui_input_field;
LUMIX_ENGINE_API extern const ComponentType gui_rect;
LUMIX_ENGINE_API extern const ComponentType gui_button;
LUMIX_ENGINE_API extern const ComponentType gui_image;
LUMIX_ENGINE_API extern const ComponentType gui_text;
LUMIX_ENGINE_API extern const ComponentType lua_script;
LUMIX_ENGINE_API extern const ComponentType lua_script_inline;
LUMIX_ENGINE_API extern const ComponentType navmesh_zone;
LUMIX_ENGINE_API extern const ComponentType navmesh_agent;
LUMIX_ENGINE_API extern const ComponentType physical_heightfield;
LUMIX_ENGINE_API extern const ComponentType d6_joint;
LUMIX_ENGINE_API extern const ComponentType distance_joint;
LUMIX_ENGINE_API extern const ComponentType hinge_joint;
LUMIX_ENGINE_API extern const ComponentType spherical_joint;
LUMIX_ENGINE_API extern const ComponentType physical_controller;
LUMIX_ENGINE_API extern const ComponentType rigid_actor;
LUMIX_ENGINE_API extern const ComponentType wheel;
LUMIX_ENGINE_API extern const ComponentType vehicle;
LUMIX_ENGINE_API extern const ComponentType physical_instanced_cube;
LUMIX_ENGINE_API extern const ComponentType physical_instanced_mesh;
LUMIX_ENGINE_API extern const ComponentType camera;
LUMIX_ENGINE_API extern const ComponentType decal;
LUMIX_ENGINE_API extern const ComponentType environment;
LUMIX_ENGINE_API extern const ComponentType point_light;
LUMIX_ENGINE_API extern const ComponentType reflection_probe;
LUMIX_ENGINE_API extern const ComponentType environment_probe;
LUMIX_ENGINE_API extern const ComponentType bone_attachment;
LUMIX_ENGINE_API extern const ComponentType particle_emitter;
LUMIX_ENGINE_API extern const ComponentType instanced_model;
LUMIX_ENGINE_API extern const ComponentType model_instance;
LUMIX_ENGINE_API extern const ComponentType curve_decal;
LUMIX_ENGINE_API extern const ComponentType terrain;
LUMIX_ENGINE_API extern const ComponentType procedural_geom;
}
