// Generated by meta.cpp

reflection::build_module("core")
	.cmp<&CoreModule::createSpline, &CoreModule::destroySpline>("spline", "Core / Spline")
		.blob_property<&CoreModule::getSplineBlob, &CoreModule::setSplineBlob>("Blob")
	.cmp<&CoreModule::createSignal, &CoreModule::destroySignal>("signal", "Core / Signal")
		.blob_property<&CoreModule::getSignalBlob, &CoreModule::setSignalBlob>("Blob")
;

