-- Generated by meta.cpp


export type Vec2 = {number}
export type Vec3 = {number}
export type Color = {number}
export type Quat = {number}
export type DVec3 = {number}
declare ImGui: {
	AlignTextToFramePadding : () -> (),
	Begin : (string, boolean?) -> (boolean, boolean?),
	BeginChildFrame : (string, number, number) -> boolean,
	BeginMenu : (string, boolean) -> boolean,
	BeginPopup : (string) -> boolean,
	Button : (string) -> boolean,
	CalcTextSize : (string) -> (number, number),
	Checkbox : (string, boolean) -> (boolean, boolean),
	CloseCurrentPopup : () -> (),
	CollapsingHeader : (string) -> boolean,
	Columns : (number) -> (),
	DragFloat : (string, number) -> (boolean, number),
	DragInt : (string, number) -> (boolean, number),
	Dummy : (number, number) -> (),
	End : () -> (),
	EndChildFrame : () -> (),
	EndCombo : () -> (),
	EndMenu : () -> (),
	EndPopup : () -> (),
	GetColumnWidth : (number) -> number,
	GetDisplayWidth : () -> number,
	GetDisplayHeight : () -> number,
	GetOsImePosRequest : () -> (number, number),
	GetWindowWidth : () -> (),
	GetWindowHeight : () -> (),
	GetWindowPos : () -> any,
	Indent : (number) -> (),
	InputTextMultiline : (string, string) -> (boolean, string?),
	InputTextMultilineWithCallback : (string, string, (string, number, boolean) -> ()) -> (boolean, string?),
	InputText : (string, string) -> (boolean, string?),
	IsItemHovered : () -> boolean,
	IsKeyPressed : (number, boolean) -> boolean,
	IsMouseClicked : (number) -> boolean,
	IsMouseDown : (number) -> boolean,
	LabelText : (string, string) -> (),
	NewLine : () -> (),
	NextColumn : () -> (),
	OpenPopup : (string) -> (),
	PlotLines : (string, {number}, Vec2) -> (),
	PopItemWidth : () -> (),
	PopID : () -> (),
	PopStyleColor : (number) -> (),
	PopStyleVar : (number) -> (),
	PopItemWidth : () -> (),
	PushItemWidth : (number) -> (),
	PushID : (number) -> (),
	PushStyleColor : (number, any) -> (),
	PushStyleVar : (number, number, number) -> () | (number, number) -> () ,
	Rect : (number, number, number) -> (),
	SameLine : () -> (),
	Selectable : (string, boolean) -> boolean | (string) -> boolean,
	Separator : () -> (),
	SetCursorScreenPos : (number, number) -> (),
	SetKeyboardFocusHere : (number) -> (),
	SetNextWindowPos : (number, number) -> (),
	SetNextWindowPosCenter : () -> (),
	SetNextWindowSize : (number, number) -> (),
	SetStyleColor : (number, any) -> (),
	SliderFloat : (string, number, number, number) -> (boolean, number),
	Text : (string) -> (),
	Unindent : (number) -> (),
	
	Key_DownArrow : number,
	Key_Enter : number,
	Key_Escape : number,
	Key_UpArrow : number
}

export type Resource = {
	newEmpty: (Resource, string) -> Resource,
	getPath: (Resource) -> string,
	path : string,
}

declare black.h : {
	Resource : Resource,
	Entity : Entity
}

export type World = {
	getActivePartition : (World) -> number,
	setActivePartition : (World, number) -> (),
	createPartition : (World, string) -> number,
	destroyPartition : (World, number) -> (),
	load : (World, string, any) -> (),
	getModule : (World, string) -> any,
	createEntity : (World) -> Entity,
	createEntityEx : (World, any) -> Entity,
	destroyEntity : (Entity) -> (),
	findEntityByName : (World, Entity, string) -> Entity,
}


export type Entity = {
	NULL : Entity,
	world : World,
	name : string,
	parent : Entity?,
	rotation : any,
	position : Vec3,
	scale : Vec3,
	hasComponent : (Entity, any) -> boolean,
	getComponent : (Entity, any) -> any,
	destroy : (Entity) -> (),
	createComponent : (Entity, any) -> any,
}


declare this : Entity
	
	type ActionDesc = {
		name : string,
		label : string,
		run : () -> ()
	}
	
	declare Editor: {
		RESOURCE_PROPERTY : number,
		COLOR_PROPERTY : number,
		ENTITY_PROPERTY : number,
		BOOLEAN_PROPERTY : number,
		setPropertyType : (any, string, number, string?) -> (),
		setArrayPropertyType : (any, string, number, string?) -> (),
		getSelectedEntitiesCount : () -> number,
		getSelectedEntity : (number) -> Entity,
		addAction : (ActionDesc) -> (),
		createEntityEx : (any) -> Entity,
		scene_view : SceneView,
		asset_browser : AssetBrowser
	}
	
	declare black.hAPI: {
		hasFilesystemWork : () -> boolean,
		
		engine : any,
		logError : (string) -> (),
		logInfo : (string) -> (),
		loadResource : (any, path:string, restype:string) -> any,
		writeFile : (string, string) -> boolean
	}
	
	
	type InputDevice = {
		type : "mouse" | "keyboard",
		index : number
	}
	
	type AxisInputEvent = {
		type : "axis",
		device : InputDevice,
		x : number,
		y : number,
		x_abs : number,
		y_abs : number
	}
	
	type ButtonInputEvent = {
		type : "button",
		device : InputDevice,
		key_id : number,
		down : boolean,
		is_repeat : boolean,
		x : number,
		y : number
	}
	
	export type InputEvent = ButtonInputEvent | AxisInputEvent
	
