// Generated by meta.cpp

reflection::build_module("gui_ng")
	.function<(ui::Document* (GUINGModule::*)())&GUINGModule::getDocument>("getDocument")
	.function<(bool (GUINGModule::*)())&GUINGModule::isReady>("isReady")
;

