// generated by meta.cpp

reflection::build_module("animation")
	.cmp<&AnimationModule::createAnimable, &AnimationModule::destroyAnimable>("animable", "Animation / Animable")
		.prop<&AnimationModule::getAnimableAnimation, &AnimationModule::setAnimableAnimation>("Animation")
	.cmp<&AnimationModule::createAnimator, &AnimationModule::destroyAnimator>("animator", "Animation / Animator")
		.function<(void (AnimationModule::*)(EntityRef entity, u32 idx))&AnimationModule::applyAnimatorSet>("applySet", "AnimationModule::applyAnimatorSet")
		.function<(void (AnimationModule::*)(EntityRef entity, u32 input_idx, bool value))&AnimationModule::setAnimatorInput>("setBoolInput", "AnimationModule::setAnimatorInput")
		.function<(void (AnimationModule::*)(EntityRef entity, u32 input_idx, float value))&AnimationModule::setAnimatorInput>("setFloatInput", "AnimationModule::setAnimatorInput")
		.function<(void (AnimationModule::*)(EntityRef entity, u32 input_idx, Vec3 value))&AnimationModule::setAnimatorInput>("setVec3Input", "AnimationModule::setAnimatorInput")
		.function<(int (AnimationModule::*)(EntityRef entity, const char* name))&AnimationModule::getAnimatorInputIndex>("getInputIndex", "AnimationModule::getAnimatorInputIndex")
		.prop<&AnimationModule::getAnimatorSource, &AnimationModule::setAnimatorSource>("Source")
			.resourceAttribute(anim::Controller::TYPE)
		.prop<&AnimationModule::getAnimatorUseRootMotion, &AnimationModule::setAnimatorUseRootMotion>("Use root motion")
		.prop<&AnimationModule::getAnimatorDefaultSet, &AnimationModule::setAnimatorDefaultSet>("Default set")
	.cmp<&AnimationModule::createPropertyAnimator, &AnimationModule::destroyPropertyAnimator>("property_animator", "Animation / Property animator")
		.prop<&AnimationModule::isPropertyAnimatorEnabled, &AnimationModule::enablePropertyAnimator>("Enabled")
		.prop<&AnimationModule::getPropertyAnimatorLooped, &AnimationModule::setPropertyAnimatorLooped>("Looped")
		.prop<&AnimationModule::getPropertyAnimatorAnimation, &AnimationModule::setPropertyAnimatorAnimation>("Animation")
			.resourceAttribute(PropertyAnimation::TYPE)
;

