name: tests
on:
  push:
    paths:
      - '**/particle_script*'
      - 'src/ui/**'
      - 'src/tests/ui_*'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - '**/particle_script*'
      - 'src/ui/**'
      - 'src/tests/ui_*'
      - '.github/workflows/tests.yml'

jobs:
  run-tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5
      
      - name: Run headless tests
        shell: cmd
        run: |
          echo Running headless tests because related files changed
          scripts\run_tests.bat

  run-tests-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libfreetype6-dev libgl1-mesa-dev libx11-dev libxi-dev libgtk-3-dev

      - name: Run headless tests
        run: ./scripts/run_tests.sh
